# Generated by Django 3.0 on 2019-12-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=500)),
                ('root_cause', models.CharField(max_length=500)),
                ('cause', models.CharField(max_length=500)),
                ('cause_type', models.CharField(max_length=500)),
                ('channel', models.CharField(max_length=500)),
                ('mark_result', models.CharField(max_length=500)),
            ],
        ),
    ]
